# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Baari < Formula
  desc "baari — cross-repo agent coordination CLI"
  homepage "https://nauman.github.io/baari/"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nauman/baari/releases/download/v0.2.2/baari_Darwin_x86_64.tar.gz"
      sha256 "d5cd1be5dcb29b45ae09594c7659425f84412eea767777af00d0224c5b94cbbf"

      define_method(:install) do
        bin.install "baari"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nauman/baari/releases/download/v0.2.2/baari_Darwin_arm64.tar.gz"
      sha256 "aae8364b389ca7ef84236fdc2464e6bc02bafb6c18ac497c2939444eadb8e9c4"

      define_method(:install) do
        bin.install "baari"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nauman/baari/releases/download/v0.2.2/baari_Linux_x86_64.tar.gz"
      sha256 "54682df64d9a550c77a7b6f61e37c5ab490305e663331a25cd1768a757ae5424"
      define_method(:install) do
        bin.install "baari"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nauman/baari/releases/download/v0.2.2/baari_Linux_arm64.tar.gz"
      sha256 "51d2fe5a7f2ce3f1c116c915d147f08fa8c831d8eee21c9cd2e111087a0eb15d"
      define_method(:install) do
        bin.install "baari"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/baari version")
  end
end
