# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Baari < Formula
  desc "baari — cross-repo agent coordination CLI"
  homepage "https://nauman.github.io/baari/"
  version "0.21.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nauman/baari/releases/download/v0.21.0/baari_Darwin_x86_64.tar.gz"
      sha256 "4fd613cc3cba4b86e966d09409fec3bad5a6c5240648a727abd7dfc9082324d7"

      define_method(:install) do
        bin.install "baari"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nauman/baari/releases/download/v0.21.0/baari_Darwin_arm64.tar.gz"
      sha256 "33b356fef0cdbd9f47320a4eef19145284d65cbee91b5428be20d44c56cf4089"

      define_method(:install) do
        bin.install "baari"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nauman/baari/releases/download/v0.21.0/baari_Linux_x86_64.tar.gz"
      sha256 "969291b92c2b449488f2a7e67c56de613e439af60cc677c5dcd6d3c41c4149bc"
      define_method(:install) do
        bin.install "baari"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nauman/baari/releases/download/v0.21.0/baari_Linux_arm64.tar.gz"
      sha256 "059fda3b389cd26c7da47af3d3b0cbb13f0eb4241ad5190e0d0cb00d8b03cc74"
      define_method(:install) do
        bin.install "baari"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/baari version")
  end
end
