# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kuickr < Formula
  desc "kuickr CLI — host your repo's docs on kuickr.co from the terminal"
  homepage "https://kuickr.co/cli"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nauman/kuickr-cli-releases/releases/download/v0.4.0/kuickr_Darwin_x86_64.tar.gz"
      sha256 "589c86f7adb6e4280773e595b32cc15ffca9d94c232b580952a03ca91017e733"

      define_method(:install) do
        bin.install "kuickr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nauman/kuickr-cli-releases/releases/download/v0.4.0/kuickr_Darwin_arm64.tar.gz"
      sha256 "2afebb7ebb9f6f43f9d7e546fef76d520e2b1bb98d91cb41c01502c010889123"

      define_method(:install) do
        bin.install "kuickr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nauman/kuickr-cli-releases/releases/download/v0.4.0/kuickr_Linux_x86_64.tar.gz"
      sha256 "496cd3b5bce8d64814f7ea0378c562216bea4ed9723e8e7f5b3239a5030e8a14"
      define_method(:install) do
        bin.install "kuickr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nauman/kuickr-cli-releases/releases/download/v0.4.0/kuickr_Linux_arm64.tar.gz"
      sha256 "1ace90a5994ecc3067f50e424d60260c3ab61c2d7572798e541fb6f8169d4a23"
      define_method(:install) do
        bin.install "kuickr"
      end
    end
  end

  test do
    system "#{bin}/kuickr", "version"
  end
end
