# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kuickr < Formula
  desc "kuickr CLI — host your repo's docs on kuickr.co from the terminal"
  homepage "https://kuickr.co/cli"
  version "0.31.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nauman/kuickr-cli-releases/releases/download/v0.31.0/kuickr_Darwin_x86_64.tar.gz"
      sha256 "a5502895e24bbce0491f4ffe872cf8e447060cd4b332ae2f5c0757b49197471f"

      define_method(:install) do
        bin.install "kuickr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nauman/kuickr-cli-releases/releases/download/v0.31.0/kuickr_Darwin_arm64.tar.gz"
      sha256 "920d4c20a20a265455e6c7fa2cd5c21e996c0a77249345825b4b0bf553df1e24"

      define_method(:install) do
        bin.install "kuickr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nauman/kuickr-cli-releases/releases/download/v0.31.0/kuickr_Linux_x86_64.tar.gz"
      sha256 "1901434a20a03edd19ac52b9c9a10768f224c56d23539217ae09ceec9ac4632a"
      define_method(:install) do
        bin.install "kuickr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nauman/kuickr-cli-releases/releases/download/v0.31.0/kuickr_Linux_arm64.tar.gz"
      sha256 "1d4d10004a019d31ca7d1de8ef9f09055c5e9635f17cbe00dbb13c3f5ac403f3"
      define_method(:install) do
        bin.install "kuickr"
      end
    end
  end

  test do
    system "#{bin}/kuickr", "version"
  end
end
